kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: fiap-rm341182
  selfLink: /apis/project.openshift.io/v1/projects/fiap-rm341182
  uid: 8e1cbe18-261d-4964-82a6-3833c7e4df2a
  resourceVersion: '17639548'
  creationTimestamp: '2022-01-11T05:52:17Z'
  annotations:
    openshift.io/description: ''
    openshift.io/display-name: ''
    openshift.io/requester: kkamsz
    openshift.io/sa.scc.mcs: 's0:c45,c30'
    openshift.io/sa.scc.supplemental-groups: 1002040000/10000
    openshift.io/sa.scc.uid-range: 1002040000/10000
  managedFields:
    - manager: cluster-policy-controller
      operation: Update
      apiVersion: v1
      time: '2022-01-11T05:52:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:openshift.io/sa.scc.mcs': {}
            'f:openshift.io/sa.scc.supplemental-groups': {}
            'f:openshift.io/sa.scc.uid-range': {}
    - manager: openshift-apiserver
      operation: Update
      apiVersion: v1
      time: '2022-01-11T05:52:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/description': {}
            'f:openshift.io/display-name': {}
            'f:openshift.io/requester': {}
        'f:status':
          'f:phase': {}
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: v1
      time: '2022-01-11T05:52:17Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:finalizers': {}
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
